### ISSUE TITLE
Python module name collision

### ISSUE THREAD

**Issue by flimberger** [projectara/greybus-spec#2]
On Ubuntu 15.04, there is a name collision with the ubuntu package python-backports.ssl-match-hostname, which provides a python package /usr/lib/python2.7/dist-packages/backports. This prevents imports from source/extensions/backports.py, which causes the build to fail. Is this an issue with sphinx in general, or specific to greybus-spec?

**Comment by gregkh** [comment]
It's specific to the extension package we are using on top of sphinx, which comes from https://github.com/jterrace/sphinxtr  

Any suggestions as to how to resolve this are appreciated, or you can just not use Ubuntu, which is always a good idea :)

**Comment by flimberger** [comment]
It's not an Ubuntu-specific issue but a general one with the python search path and packages, [I've opened an issue](https://github.com/jterrace/sphinxtr/issues/37) at the upstream repository. Possible workarounds are using a virtualenv without system site packages or renaming `source/extensions/backports.py` (and changing the import line in `source/extensions/numfig.py:5`to something else.

As I have a workaround for me and an issue filed upstream, I think this issue can be closed as it is not directly related to the spec.
